package registrar

import (
	"fmt"
	"strings"

	"golang.org/x/net/idna"
)

// ValidateDomainName checks that name conforms to RFC 5730/5731 LDH rules.
// Empty string passes without error — presence validation is the registrar's job.
// xn-- prefixed ACE labels (RFC 5891) are accepted as-is without further validation.
// Returns *EPPError{Code: 2005} on any violation.
func ValidateDomainName(name string) error {
	if name == "" {
		return nil
	}
	if len(name) > 255 {
		return &EPPError{Code: 2005, Message: fmt.Sprintf("domain name too long: %d chars (max 255)", len(name))}
	}
	labels := strings.Split(name, ".")
	for _, label := range labels {
		if err := validateLabel(label); err != nil {
			return &EPPError{Code: 2005, Message: fmt.Sprintf("domain name label %q: %v", label, err)}
		}
	}
	return nil
}

// validateLabel checks a single DNS label for LDH compliance.
// Labels beginning with "xn--" (case-insensitive ACE labels per RFC 5891) pass
// without further validation.
func validateLabel(label string) error {
	if len(label) == 0 || len(label) > 63 {
		return fmt.Errorf("label length must be 1–63 chars, got %d", len(label))
	}
	// ACE labels: xn-- prefix signals IDN encoding — accept as-is per D-03.
	if strings.HasPrefix(strings.ToLower(label), "xn--") {
		return nil
	}
	if label[0] == '-' || label[len(label)-1] == '-' {
		return fmt.Errorf("label must not start or end with hyphen")
	}
	for _, ch := range label {
		if !isLDH(ch) {
			return fmt.Errorf("character %q not allowed (LDH: letters, digits, hyphen only)", ch)
		}
	}
	return nil
}

// isLDH reports whether ch is a valid LDH (Letter, Digit, Hyphen) character
// per RFC 952 / RFC 1123. Strictly ASCII-only — unicode letters are not LDH.
func isLDH(ch rune) bool {
	return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || (ch >= '0' && ch <= '9') || ch == '-'
}

// ValidateContactHandle checks that id conforms to [A-Za-z0-9-]+, 1–64 chars.
// Empty string passes without error — presence validation is the registrar's job.
// The 64-char limit accommodates RUN_ID-prefixed handles generated by the scenario
// runner (8-hex prefix + "-" + base ID) without exceeding typical registrar limits.
// Returns *EPPError{Code: 2005} on any violation.
func ValidateContactHandle(id string) error {
	if id == "" {
		return nil
	}
	if len(id) > 64 {
		return &EPPError{Code: 2005, Message: fmt.Sprintf("contact handle length must be 1–64 chars, got %d", len(id))}
	}
	for _, ch := range id {
		if !isLDH(ch) {
			return &EPPError{Code: 2005, Message: fmt.Sprintf("contact handle character %q not allowed ([A-Za-z0-9-] only)", ch)}
		}
	}
	return nil
}

// ValidateAuthInfo checks that authInfo consists of printable ASCII characters
// (0x20–0x7E), 6–64 chars.
// Empty string passes without error — presence validation is the registrar's job.
// Returns *EPPError{Code: 2005} on any violation.
func ValidateAuthInfo(authInfo string) error {
	if authInfo == "" {
		return nil
	}
	if len(authInfo) < 6 || len(authInfo) > 64 {
		return &EPPError{Code: 2005, Message: fmt.Sprintf("auth-info length must be 6–64 chars, got %d", len(authInfo))}
	}
	for _, ch := range authInfo {
		if ch < 0x20 || ch > 0x7E {
			return &EPPError{Code: 2005, Message: fmt.Sprintf("auth-info character %q is not printable ASCII (0x20–0x7E)", ch)}
		}
	}
	return nil
}

// ValidateHostName checks that name conforms to RFC 5730/5731 LDH rules.
// This delegates to ValidateDomainName as host name constraints are identical.
// Empty string passes without error — presence validation is the registrar's job.
// Returns *EPPError{Code: 2005} on any violation.
func ValidateHostName(name string) error {
	return ValidateDomainName(name)
}

// NormalizeToACE converts a (possibly unicode/IDN) domain name to its ASCII-Compatible
// Encoding (ACE / Punycode) form per RFC 5891, e.g. "münchen.de" → "xn--mnchen-3ya.de".
// Pure-ASCII and already-ACE names pass through unchanged. Empty string passes (presence
// validation is the registrar's job). Returns ("", *EPPError{Code:2005}) on conversion failure.
func NormalizeToACE(name string) (string, error) {
	if name == "" {
		return "", nil
	}
	ace, err := idna.Lookup.ToASCII(name)
	if err != nil {
		return "", &EPPError{Code: 2005, Message: fmt.Sprintf("domain name %q: IDN/ACE conversion failed: %v", name, err)}
	}
	return ace, nil
}
