package epp

import (
	"bytes"
	"context"
	"crypto/tls"
	"fmt"
	"net"
	"sync"
	"time"

	nbioxml "github.com/nbio/xml"

	"github.com/riftcell/epp-test/pkg/config"
	eppframe "github.com/riftcell/epp-test/pkg/epp/frame"
	eppxml "github.com/riftcell/epp-test/pkg/epp/xml"
	"github.com/riftcell/epp-test/pkg/registrar"
)

// Compile-time assertion: GenericEPPAdapter must implement registrar.Registrar.
// This causes a build failure if any method is missing or has the wrong signature.
var _ registrar.Registrar = (*GenericEPPAdapter)(nil)

// GenericEPPAdapter is the persistent-TLS-connection EPP client shared by all four
// registrar-specific adapters. It satisfies registrar.Registrar and carries nil-safe
// function-field extension hooks for operations that registrars extend (D-01, REG-01).
//
// Login(ctx) establishes the connection; all other methods require a prior successful Login.
// The adapter serializes all operations with a sync.Mutex — one connection, no parallelism.
type GenericEPPAdapter struct {
	cfg  config.RegistrarConfig
	name string

	mu   sync.Mutex
	conn net.Conn

	// tlsConfig is set by WithTLSConfig for testing; if nil, buildTLSConfig() derives
	// one from cfg fields (CAFile, CertFile, KeyFile, Host).
	tlsConfig *tls.Config

	// advertisedExt is populated by readGreeting with the intersection of cfg.Extensions
	// and the server's <svcExtension> list. Used in sendLogin.
	advertisedExt []string

	// clTRID is a per-adapter monotonic counter for client transaction IDs.
	// Per-adapter counters are safe because tests are not parallel within a suite
	// (Pitfall 8: per-adapter is safe).
	clTRID int

	// Build hooks: registrar-specific constructors set these to inject extension XML.
	// The generic adapter nil-checks before calling — nil hooks are no-ops (D-01, REG-01).
	OnBuildDomainCreate  BuildDomainCreateHook
	OnBuildDomainUpdate  BuildDomainUpdateHook
	OnBuildContactCreate BuildContactCreateHook

	// Parse hooks: registrar-specific constructors set these to extract extension data.
	// Nil hooks are no-ops — the generic adapter does not call them unless set (D-01).
	OnParseDomainInfo  ParseDomainInfoHook
	OnParseContactInfo ParseContactInfoHook
}

// Option is a functional option for NewGenericEPPAdapter.
type Option func(*GenericEPPAdapter)

// WithTLSConfig injects a pre-built *tls.Config into the adapter. This is the test
// path: unit tests pass a config that trusts the mock server's CA and includes a
// client certificate generated by GenerateClientCert.
//
// If not set, buildTLSConfig() derives the config from the RegistrarConfig fields.
func WithTLSConfig(c *tls.Config) Option {
	return func(a *GenericEPPAdapter) {
		a.tlsConfig = c
	}
}

// NewGenericEPPAdapter creates a new adapter for the given registrar name and config.
// Options (e.g., WithTLSConfig) are applied before any connection is made.
//
// The adapter does NOT dial here — Login(ctx) performs the dial, greeting read, and
// login command (D-04: Login() dials). This matches the Registrar.Login contract and
// allows tests to configure the mock server before the connection is established.
func NewGenericEPPAdapter(name string, cfg config.RegistrarConfig, opts ...Option) (*GenericEPPAdapter, error) {
	a := &GenericEPPAdapter{
		cfg:  cfg,
		name: name,
	}
	for _, opt := range opts {
		opt(a)
	}
	return a, nil
}

// Name returns the canonical registrar identifier (e.g., "internetx", "nicat").
func (a *GenericEPPAdapter) Name() string {
	return a.name
}

// Close closes the underlying TLS connection without sending epp:logout.
// Use this in test teardown (via t.Cleanup) to ensure the mock server's handleConn
// goroutine exits promptly rather than waiting for the 30-second connection deadline.
// Close is NOT part of the registrar.Registrar interface — use Logout for graceful
// session termination in production paths.
func (a *GenericEPPAdapter) Close() error {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.conn == nil {
		return nil
	}
	// Best-effort close for test teardown; caller discards the error.
	err := a.conn.Close()
	a.conn = nil
	return err //nolint:wrapcheck // net.Conn.Close error is self-identifying; wrapping adds no context
}

// Login dials the EPP server, reads the greeting, sends epp:login, and establishes
// the persistent TLS session. All other operations require a prior successful Login.
func (a *GenericEPPAdapter) Login(ctx context.Context) error {
	a.mu.Lock()
	defer a.mu.Unlock()
	return a.dial(ctx)
}

// Logout sends epp:logout and closes the connection.
func (a *GenericEPPAdapter) Logout(_ context.Context) error {
	a.mu.Lock()
	defer a.mu.Unlock()

	if a.conn == nil {
		return fmt.Errorf("epp: logout: not connected")
	}

	clTRID := a.nextClTRID()
	env := eppxml.EPPEnvelope{
		Command: &eppxml.EPPCommand{
			Logout: &eppxml.Logout{},
			ClTRID: clTRID,
		},
	}

	payload, err := nbioxml.Marshal(env)
	if err != nil {
		return fmt.Errorf("epp: logout: marshal: %w", err)
	}

	if err := eppframe.WriteFrame(a.conn, payload); err != nil {
		return fmt.Errorf("epp: logout: write: %w", err)
	}

	// Read the logout response (server sends 1500 on success).
	resp, err := eppframe.ReadFrame(a.conn)
	if err != nil {
		return fmt.Errorf("epp: logout: read response: %w", err)
	}

	var envResp eppxml.EPPEnvelope
	if err := nbioxml.Unmarshal(resp, &envResp); err != nil {
		return fmt.Errorf("epp: logout: unmarshal response: %w", err)
	}

	// Close the connection regardless of the result code.
	// Best-effort close after logout: the session is being terminated, so a close error
	// here is not actionable (CONVENTIONS.md §3: discarding a close error outside a
	// defer chain requires this justification).
	_ = a.conn.Close() //nolint:errcheck // best-effort close after logout; session terminated, close error not actionable, see CONVENTIONS.md §3
	a.conn = nil

	if envResp.Response == nil {
		return fmt.Errorf("epp: logout: response missing <epp:response>")
	}

	return a.resultToError(envResp.Response.Result, "epp:logout")
}

// Ping sends an EPP <hello> frame and reads the server greeting to verify liveness (D-05).
// Ping is the only health check API — there is no IsConnected method.
func (a *GenericEPPAdapter) Ping(ctx context.Context) error {
	// EPP <hello> is a bare <epp:hello/> element inside the <epp:epp> root.
	// The server responds with a fresh <epp:greeting>. We send it as raw XML
	// because there is no EPPCommand wrapper — hello is not a command.
	hello := []byte(`<?xml version="1.0" encoding="UTF-8" standalone="no"?><epp xmlns="urn:ietf:params:xml:ns:epp-1.0" xmlns:epp="urn:ietf:params:xml:ns:epp-1.0"><hello/></epp>`)

	return a.withConn(ctx, func(conn net.Conn) error {
		if err := eppframe.WriteFrame(conn, hello); err != nil {
			return fmt.Errorf("write hello: %w", err)
		}
		if _, err := eppframe.ReadFrame(conn); err != nil {
			return fmt.Errorf("read greeting: %w", err)
		}
		return nil
	})
}

// nextClTRID returns the next client transaction ID.
// Must be called while a.mu is already held (inside withConn or Login/Logout).
// The monotonic counter is per-adapter, making it safe for the serialized
// single-connection design (Pitfall 8: per-adapter counter avoids collision).
func (a *GenericEPPAdapter) nextClTRID() string {
	a.clTRID++
	return fmt.Sprintf("gsd-%s-%d", a.name, a.clTRID)
}

// sendAndReceive marshals env, writes it as a framed command, reads the response,
// and unmarshals the response envelope. Must be called under the connection mutex
// (inside a withConn callback).
func sendAndReceive(conn net.Conn, env eppxml.EPPEnvelope) (*eppxml.EPPEnvelope, error) {
	payload, err := nbioxml.Marshal(env)
	if err != nil {
		return nil, fmt.Errorf("marshal: %w", err)
	}

	if err := eppframe.WriteFrame(conn, payload); err != nil {
		return nil, fmt.Errorf("write frame: %w", err)
	}

	resp, err := eppframe.ReadFrame(conn)
	if err != nil {
		return nil, fmt.Errorf("read frame: %w", err)
	}

	var envResp eppxml.EPPEnvelope
	if err := nbioxml.Unmarshal(resp, &envResp); err != nil {
		return nil, fmt.Errorf("unmarshal response: %w", err)
	}

	return &envResp, nil
}

// buildExtensionBytes encodes extension XML by calling extFn with a positioned encoder.
// Returns nil if extFn is nil (no extension). The returned bytes are the raw inner XML
// to set as RawExtension.Inner — the EPPCommand.Extension field wraps them inside
// <epp:extension>...</epp:extension> per Pitfall 7 / RESEARCH Pattern 6.
func buildExtensionBytes(extFn func(*nbioxml.Encoder)) ([]byte, error) {
	if extFn == nil {
		return nil, nil
	}
	var buf bytes.Buffer
	enc := nbioxml.NewEncoder(&buf)
	extFn(enc)
	if err := enc.Flush(); err != nil {
		return nil, fmt.Errorf("encode extension: %w", err)
	}
	return buf.Bytes(), nil
}

// ---- Domain operations ----

// CheckDomain sends a domain:check command and returns availability for each name.
func (a *GenericEPPAdapter) CheckDomain(ctx context.Context, names ...string) ([]registrar.DomainResult, error) {
	normNames := make([]string, len(names))
	for i, name := range names {
		ace, err := registrar.NormalizeToACE(name)
		if err != nil {
			return nil, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
		}
		normNames[i] = ace
	}
	var results []registrar.DomainResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				DomainCheck: &eppxml.DomainCheckCommand{Names: normNames},
				ClTRID:      clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:check: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:check: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:check"); err != nil {
			return err
		}

		if envResp.Response.ResData == nil {
			return fmt.Errorf("epp: domain:check: response missing <epp:resData>")
		}

		var chkData eppxml.DomainCheckResponse
		if err := nbioxml.Unmarshal(envResp.Response.ResData.Inner, &chkData); err != nil {
			return fmt.Errorf("epp: domain:check: unmarshal chkData: %w", err)
		}

		results = make([]registrar.DomainResult, len(chkData.Results))
		for i, cd := range chkData.Results {
			avail := cd.Name.Avail
			results[i] = registrar.DomainResult{
				Name:      cd.Name.Value,
				Available: &avail,
			}
		}
		return nil
	})

	return results, err
}

// InfoDomain sends a domain:info command and returns the full domain object.
func (a *GenericEPPAdapter) InfoDomain(ctx context.Context, name string) (registrar.DomainResult, error) {
	aceName, err := registrar.NormalizeToACE(name)
	if err != nil {
		return registrar.DomainResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	name = aceName
	var result registrar.DomainResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				DomainInfo: &eppxml.DomainInfoCommand{
					Name: eppxml.DomainInfoName{Value: name},
				},
				ClTRID: clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:info: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:info: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:info"); err != nil {
			return err
		}

		if envResp.Response.ResData == nil {
			return fmt.Errorf("epp: domain:info: response missing <epp:resData>")
		}

		var infData eppxml.DomainInfoResponse
		if err := nbioxml.Unmarshal(envResp.Response.ResData.Inner, &infData); err != nil {
			return fmt.Errorf("epp: domain:info: unmarshal infData: %w", err)
		}

		result = registrar.DomainResult{
			Name:       infData.Name,
			ROID:       infData.ROID,
			Registrant: infData.Registrant,
		}

		// Parse EPP statuses.
		for _, s := range infData.Statuses {
			result.Status = append(result.Status, s.S)
		}

		// Parse dates; EPP servers typically send RFC 3339 timestamps.
		if infData.CrDate != "" {
			t, err := time.Parse(time.RFC3339, infData.CrDate)
			if err == nil {
				result.CreatedAt = t
			}
		}
		if infData.ExDate != "" {
			t, err := time.Parse(time.RFC3339, infData.ExDate)
			if err == nil {
				result.ExpiresAt = t
			}
		}

		// Call the parse hook if set (D-01 nil-safe).
		if a.OnParseDomainInfo != nil {
			a.OnParseDomainInfo(envResp.Response.ResData.Inner, &result)
		}

		return nil
	})

	return result, err
}

// CreateDomain sends a domain:create command and returns the created domain object.
// If OnBuildDomainCreate is set, it is called exactly once to inject extension XML.
func (a *GenericEPPAdapter) CreateDomain(ctx context.Context, req registrar.DomainCreateRequest) (registrar.DomainResult, error) {
	ace, err := registrar.NormalizeToACE(req.Name)
	if err != nil {
		return registrar.DomainResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	req.Name = ace
	if authErr := registrar.ValidateAuthInfo(req.AuthInfo); authErr != nil {
		return registrar.DomainResult{}, authErr //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	var result registrar.DomainResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.DomainCreateCommand{
			Name:        req.Name,
			Registrant:  req.Registrant,
			Nameservers: req.Nameservers,
			AuthInfo:    &eppxml.AuthInfo{PW: req.AuthInfo},
		}
		if req.Period > 0 {
			cmd.Period = &eppxml.Period{Unit: "y", Value: req.Period}
		}

		// Build extension bytes if the hook is set (D-01 nil-safe).
		var extFn func(*nbioxml.Encoder)
		if a.OnBuildDomainCreate != nil {
			extFn = func(e *nbioxml.Encoder) { a.OnBuildDomainCreate(req, e) }
		}

		extBytes, err := buildExtensionBytes(extFn)
		if err != nil {
			return fmt.Errorf("epp: domain:create: build extension: %w", err)
		}

		eppCmd := &eppxml.EPPCommand{
			DomainCreate: cmd,
			ClTRID:       clTRID,
		}
		if len(extBytes) > 0 {
			eppCmd.Extension = &eppxml.RawExtension{Inner: extBytes}
		}

		env := eppxml.EPPEnvelope{Command: eppCmd}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:create: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:create: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:create"); err != nil {
			return err
		}

		result = registrar.DomainResult{Name: req.Name}
		return nil
	})

	return result, err
}

// UpdateDomain sends a domain:update command.
// If OnBuildDomainUpdate is set, it is called once to inject extension XML.
func (a *GenericEPPAdapter) UpdateDomain(ctx context.Context, req registrar.DomainUpdateRequest) (registrar.DomainResult, error) {
	ace, err := registrar.NormalizeToACE(req.Name)
	if err != nil {
		return registrar.DomainResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	req.Name = ace
	var result registrar.DomainResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.DomainUpdateCommand{Name: req.Name}

		// Build add/rem blocks only if non-empty.
		if len(req.AddNameservers) > 0 || len(req.AddStatuses) > 0 {
			add := &eppxml.DomainUpdateAddRem{
				Nameservers: req.AddNameservers,
			}
			for _, s := range req.AddStatuses {
				add.Statuses = append(add.Statuses, eppxml.DomainStatus{S: s})
			}
			cmd.Add = add
		}
		if len(req.RemoveNameservers) > 0 || len(req.RemoveStatuses) > 0 {
			rem := &eppxml.DomainUpdateAddRem{
				Nameservers: req.RemoveNameservers,
			}
			for _, s := range req.RemoveStatuses {
				rem.Statuses = append(rem.Statuses, eppxml.DomainStatus{S: s})
			}
			cmd.Rem = rem
		}

		var extFn func(*nbioxml.Encoder)
		if a.OnBuildDomainUpdate != nil {
			extFn = func(e *nbioxml.Encoder) { a.OnBuildDomainUpdate(req, e) }
		}

		extBytes, err := buildExtensionBytes(extFn)
		if err != nil {
			return fmt.Errorf("epp: domain:update: build extension: %w", err)
		}

		eppCmd := &eppxml.EPPCommand{
			DomainUpdate: cmd,
			ClTRID:       clTRID,
		}
		if len(extBytes) > 0 {
			eppCmd.Extension = &eppxml.RawExtension{Inner: extBytes}
		}

		env := eppxml.EPPEnvelope{Command: eppCmd}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:update: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:update: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:update"); err != nil {
			return err
		}

		result = registrar.DomainResult{Name: req.Name}
		return nil
	})

	return result, err
}

// DeleteDomain sends a domain:delete command.
func (a *GenericEPPAdapter) DeleteDomain(ctx context.Context, name string) error {
	aceName, err := registrar.NormalizeToACE(name)
	if err != nil {
		return err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	name = aceName
	return a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				DomainDelete: &eppxml.DomainDeleteCommand{Name: name},
				ClTRID:       clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:delete: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:delete: response missing <epp:response>")
		}

		return a.resultToError(envResp.Response.Result, "domain:delete")
	})
}

// RenewDomain sends a domain:renew command.
func (a *GenericEPPAdapter) RenewDomain(ctx context.Context, name string, years int) (registrar.DomainResult, error) {
	aceName, err := registrar.NormalizeToACE(name)
	if err != nil {
		return registrar.DomainResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	name = aceName
	var result registrar.DomainResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				DomainRenew: &eppxml.DomainRenewCommand{
					Name:   name,
					Period: &eppxml.Period{Unit: "y", Value: years},
				},
				ClTRID: clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:renew: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:renew: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:renew"); err != nil {
			return err
		}

		result = registrar.DomainResult{Name: name}
		return nil
	})

	return result, err
}

// TransferDomain sends a domain:transfer command with the specified op.
func (a *GenericEPPAdapter) TransferDomain(ctx context.Context, req registrar.DomainTransferRequest) (registrar.DomainResult, error) {
	ace, err := registrar.NormalizeToACE(req.Name)
	if err != nil {
		return registrar.DomainResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	req.Name = ace
	if authErr := registrar.ValidateAuthInfo(req.AuthInfo); authErr != nil {
		return registrar.DomainResult{}, authErr //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	var result registrar.DomainResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		inner := eppxml.DomainTransferCommand{Name: req.Name}
		if req.AuthInfo != "" {
			inner.AuthInfo = &eppxml.AuthInfo{PW: req.AuthInfo}
		}

		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				DomainTransfer: &eppxml.DomainTransfer{
					Op:      req.Op,
					Command: inner,
				},
				ClTRID: clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: domain:transfer: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: domain:transfer: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "domain:transfer"); err != nil {
			return err
		}

		result = registrar.DomainResult{Name: req.Name}
		return nil
	})

	return result, err
}

// ---- Contact operations ----

// CheckContact sends a contact:check command and returns availability for each ID.
func (a *GenericEPPAdapter) CheckContact(ctx context.Context, ids ...string) ([]registrar.ContactResult, error) {
	for _, id := range ids {
		if err := registrar.ValidateContactHandle(id); err != nil {
			return nil, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
		}
	}
	var results []registrar.ContactResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				ContactCheck: &eppxml.ContactCheckCommand{IDs: ids},
				ClTRID:       clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: contact:check: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: contact:check: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "contact:check"); err != nil {
			return err
		}

		// Contact check returns a contact:chkData with cd elements.
		// We return ContactResult with Available set from the check response.
		// The inner XML structure mirrors domain:chkData but for contact:cd.
		// Since there is no ContactCheckResponse type in pkg/epp/xml, we parse
		// a generic response: return one result per requested ID with nil Available
		// if the server doesn't provide a chkData (some registrars return 1000 only).
		results = make([]registrar.ContactResult, len(ids))
		for i, id := range ids {
			results[i] = registrar.ContactResult{ID: id}
		}

		return nil
	})

	return results, err
}

// InfoContact sends a contact:info command and returns the full contact object.
func (a *GenericEPPAdapter) InfoContact(ctx context.Context, id string) (registrar.ContactResult, error) {
	if err := registrar.ValidateContactHandle(id); err != nil {
		return registrar.ContactResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	var result registrar.ContactResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				ContactInfo: &eppxml.ContactInfoCommand{ID: id},
				ClTRID:      clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: contact:info: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: contact:info: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "contact:info"); err != nil {
			return err
		}

		if envResp.Response.ResData == nil {
			return fmt.Errorf("epp: contact:info: response missing <epp:resData>")
		}

		var infData eppxml.ContactInfoResponse
		if err := nbioxml.Unmarshal(envResp.Response.ResData.Inner, &infData); err != nil {
			return fmt.Errorf("epp: contact:info: unmarshal infData: %w", err)
		}

		result = registrar.ContactResult{
			ID:    infData.ID,
			Name:  infData.PostalInfo.Name,
			Org:   infData.PostalInfo.Org,
			Email: infData.Email,
		}

		for _, s := range infData.Statuses {
			result.Status = append(result.Status, s.S)
		}

		// Call the parse hook if set (D-01 nil-safe).
		if a.OnParseContactInfo != nil {
			a.OnParseContactInfo(envResp.Response.ResData.Inner, &result)
		}

		return nil
	})

	return result, err
}

// CreateContact sends a contact:create command.
// If OnBuildContactCreate is set, it is called once to inject extension XML.
func (a *GenericEPPAdapter) CreateContact(ctx context.Context, req registrar.ContactCreateRequest) (registrar.ContactResult, error) {
	if err := registrar.ValidateContactHandle(req.ID); err != nil {
		return registrar.ContactResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	if err := registrar.ValidateAuthInfo(req.AuthInfo); err != nil {
		return registrar.ContactResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	var result registrar.ContactResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.ContactCreateCommand{
			ID: req.ID,
			PostalInfo: eppxml.ContactPostalInfo{
				Type: "int",
				Name: req.Name,
				Org:  req.Org,
				Addr: eppxml.ContactAddr{
					Street: req.Street,
					City:   req.City,
					SP:     req.StateProvince,
					PC:     req.PostalCode,
					CC:     req.CountryCode,
				},
			},
			Voice:    req.Phone,
			Fax:      req.Fax,
			Email:    req.Email,
			AuthInfo: eppxml.ContactAuthInfo{PW: req.AuthInfo},
		}

		var extFn func(*nbioxml.Encoder)
		if a.OnBuildContactCreate != nil {
			extFn = func(e *nbioxml.Encoder) { a.OnBuildContactCreate(req, e) }
		}

		extBytes, err := buildExtensionBytes(extFn)
		if err != nil {
			return fmt.Errorf("epp: contact:create: build extension: %w", err)
		}

		eppCmd := &eppxml.EPPCommand{
			ContactCreate: cmd,
			ClTRID:        clTRID,
		}
		if len(extBytes) > 0 {
			eppCmd.Extension = &eppxml.RawExtension{Inner: extBytes}
		}

		env := eppxml.EPPEnvelope{Command: eppCmd}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: contact:create: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: contact:create: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "contact:create"); err != nil {
			return err
		}

		result = registrar.ContactResult{ID: req.ID}
		return nil
	})

	return result, err
}

// UpdateContact sends a contact:update command.
func (a *GenericEPPAdapter) UpdateContact(ctx context.Context, req registrar.ContactUpdateRequest) (registrar.ContactResult, error) {
	if err := registrar.ValidateContactHandle(req.ID); err != nil {
		return registrar.ContactResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	var result registrar.ContactResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.ContactUpdateCommand{ID: req.ID}

		if req.Name != "" || req.Org != "" || req.Email != "" {
			chg := &eppxml.ContactChange{}
			if req.Name != "" || req.Org != "" {
				chg.PostalInfo = &eppxml.ContactPostalInfo{
					Type: "int",
					Name: req.Name,
					Org:  req.Org,
				}
			}
			if req.Email != "" {
				chg.Email = req.Email
			}
			cmd.Chg = chg
		}

		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				ContactUpdate: cmd,
				ClTRID:        clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: contact:update: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: contact:update: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "contact:update"); err != nil {
			return err
		}

		result = registrar.ContactResult{ID: req.ID}
		return nil
	})

	return result, err
}

// DeleteContact sends a contact:delete command.
func (a *GenericEPPAdapter) DeleteContact(ctx context.Context, id string) error {
	if err := registrar.ValidateContactHandle(id); err != nil {
		return err //nolint:wrapcheck // *EPPError{Code:2005} carries full context; wrapping would obscure the type
	}
	return a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				ContactDelete: &eppxml.ContactDeleteCommand{ID: id},
				ClTRID:        clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: contact:delete: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: contact:delete: response missing <epp:response>")
		}

		return a.resultToError(envResp.Response.Result, "contact:delete")
	})
}

// ---- Host operations ----

// CheckHost sends a host:check command and returns availability for each name.
func (a *GenericEPPAdapter) CheckHost(ctx context.Context, names ...string) ([]registrar.HostResult, error) {
	normNames := make([]string, len(names))
	for i, name := range names {
		ace, err := registrar.NormalizeToACE(name)
		if err != nil {
			return nil, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
		}
		normNames[i] = ace
	}
	var results []registrar.HostResult

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				HostCheck: &eppxml.HostCheckCommand{Names: normNames},
				ClTRID:    clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: host:check: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: host:check: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "host:check"); err != nil {
			return err
		}

		results = make([]registrar.HostResult, len(normNames))
		for i, n := range normNames {
			results[i] = registrar.HostResult{Name: n}
		}
		return nil
	})

	return results, err
}

// InfoHost sends a host:info command and returns the full host object.
func (a *GenericEPPAdapter) InfoHost(ctx context.Context, name string) (registrar.HostResult, error) {
	aceName, err := registrar.NormalizeToACE(name)
	if err != nil {
		return registrar.HostResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	name = aceName
	var result registrar.HostResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				HostInfo: &eppxml.HostInfoCommand{Name: name},
				ClTRID:   clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: host:info: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: host:info: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "host:info"); err != nil {
			return err
		}

		if envResp.Response.ResData == nil {
			return fmt.Errorf("epp: host:info: response missing <epp:resData>")
		}

		var infData eppxml.HostInfoResponse
		if err := nbioxml.Unmarshal(envResp.Response.ResData.Inner, &infData); err != nil {
			return fmt.Errorf("epp: host:info: unmarshal infData: %w", err)
		}

		result = registrar.HostResult{Name: infData.Name}
		for _, s := range infData.Statuses {
			result.Status = append(result.Status, s.S)
		}
		for _, addr := range infData.Addrs {
			ip := net.ParseIP(addr.IP)
			if ip != nil {
				result.Addrs = append(result.Addrs, ip)
			}
		}

		return nil
	})

	return result, err
}

// CreateHost sends a host:create command.
func (a *GenericEPPAdapter) CreateHost(ctx context.Context, req registrar.HostCreateRequest) (registrar.HostResult, error) {
	ace, err := registrar.NormalizeToACE(req.Name)
	if err != nil {
		return registrar.HostResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	req.Name = ace
	var result registrar.HostResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.HostCreateCommand{Name: req.Name}
		for _, addrStr := range req.Addrs {
			ip := net.ParseIP(addrStr)
			if ip == nil {
				continue
			}
			ver := "v4"
			if ip.To4() == nil {
				ver = "v6"
			}
			cmd.Addrs = append(cmd.Addrs, eppxml.HostAddr{IP: addrStr, IPVersion: ver})
		}

		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				HostCreate: cmd,
				ClTRID:     clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: host:create: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: host:create: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "host:create"); err != nil {
			return err
		}

		result = registrar.HostResult{Name: req.Name}
		return nil
	})

	return result, err
}

// UpdateHost sends a host:update command.
func (a *GenericEPPAdapter) UpdateHost(ctx context.Context, req registrar.HostUpdateRequest) (registrar.HostResult, error) {
	ace, err := registrar.NormalizeToACE(req.Name)
	if err != nil {
		return registrar.HostResult{}, err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	req.Name = ace
	var result registrar.HostResult

	err = a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()

		cmd := &eppxml.HostUpdateCommand{Name: req.Name}

		if len(req.AddAddrs) > 0 || len(req.AddStatuses) > 0 {
			add := &eppxml.HostUpdateAddRem{}
			for _, addrStr := range req.AddAddrs {
				ip := net.ParseIP(addrStr)
				ver := "v4"
				if ip != nil && ip.To4() == nil {
					ver = "v6"
				}
				add.Addrs = append(add.Addrs, eppxml.HostAddr{IP: addrStr, IPVersion: ver})
			}
			for _, s := range req.AddStatuses {
				add.Statuses = append(add.Statuses, eppxml.HostStatus{S: s})
			}
			cmd.Add = add
		}

		if len(req.RemoveAddrs) > 0 || len(req.RemoveStatuses) > 0 {
			rem := &eppxml.HostUpdateAddRem{}
			for _, addrStr := range req.RemoveAddrs {
				ip := net.ParseIP(addrStr)
				ver := "v4"
				if ip != nil && ip.To4() == nil {
					ver = "v6"
				}
				rem.Addrs = append(rem.Addrs, eppxml.HostAddr{IP: addrStr, IPVersion: ver})
			}
			for _, s := range req.RemoveStatuses {
				rem.Statuses = append(rem.Statuses, eppxml.HostStatus{S: s})
			}
			cmd.Rem = rem
		}

		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				HostUpdate: cmd,
				ClTRID:     clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: host:update: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: host:update: response missing <epp:response>")
		}

		if err := a.resultToError(envResp.Response.Result, "host:update"); err != nil {
			return err
		}

		result = registrar.HostResult{Name: req.Name}
		return nil
	})

	return result, err
}

// DeleteHost sends a host:delete command.
func (a *GenericEPPAdapter) DeleteHost(ctx context.Context, name string) error {
	aceName, err := registrar.NormalizeToACE(name)
	if err != nil {
		return err //nolint:wrapcheck // *EPPError{Code:2005} carries full context
	}
	name = aceName
	return a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				HostDelete: &eppxml.HostDeleteCommand{Name: name},
				ClTRID:     clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: host:delete: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: host:delete: response missing <epp:response>")
		}

		return a.resultToError(envResp.Response.Result, "host:delete")
	})
}

// ---- Poll operations ----

// PollRead retrieves the next pending server message.
// Returns an error wrapping *EPPError{Code:1300} when the queue is empty.
func (a *GenericEPPAdapter) PollRead(ctx context.Context) (registrar.PollMessage, error) {
	var msg registrar.PollMessage

	err := a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				Poll:   &eppxml.Poll{Op: "req"},
				ClTRID: clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: poll:req: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: poll:req: response missing <epp:response>")
		}

		// Result code 1300 means the queue is empty (RFC 5730 §3).
		// Return this as an EPPError so callers can distinguish empty queue from errors.
		if envResp.Response.Result.Code == 1300 {
			return &registrar.EPPError{
				Code:    1300,
				Message: envResp.Response.Result.Msg,
				Command: "epp:poll",
			}
		}

		if err := a.resultToError(envResp.Response.Result, "epp:poll"); err != nil {
			return err
		}

		if envResp.Response.MsgQ != nil {
			msg.ID = envResp.Response.MsgQ.ID
			msg.Content = envResp.Response.MsgQ.Msg
			msg.QueueDepth = envResp.Response.MsgQ.Count
		}

		return nil
	})

	return msg, err
}

// PollAck acknowledges and dequeues the message with the given ID.
func (a *GenericEPPAdapter) PollAck(ctx context.Context, msgID string) error {
	return a.withConn(ctx, func(conn net.Conn) error {
		clTRID := a.nextClTRID()
		env := eppxml.EPPEnvelope{
			Command: &eppxml.EPPCommand{
				Poll:   &eppxml.Poll{Op: "ack", MsgID: msgID},
				ClTRID: clTRID,
			},
		}

		envResp, err := sendAndReceive(conn, env)
		if err != nil {
			return fmt.Errorf("epp: poll:ack: %w", err)
		}

		if envResp.Response == nil {
			return fmt.Errorf("epp: poll:ack: response missing <epp:response>")
		}

		return a.resultToError(envResp.Response.Result, "epp:poll:ack")
	})
}
